### ISSUE TITLE
Issues with segmentation and packaging in Windows

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#594]
Testing version 20221003-3 on Windows 10 and segmentation doesn't appear to be working. Log shows the following error:

> C:/Program Files/dvrescue/cygwin/bin/bash.exe C:/Program Files/dvrescue/tools/dvpackager -v -X -d -t -a n -T /cygdrive/D/test001.dv.dvrescue.xml /cygdrive/D/test001.dv
> 
> Process failed to start: The system cannot find the file specified.

Path or permissions issue?

**Comment by dericed** [comment]
Thanks. Does test001.dv.dvrescue.xml and test001.dv exist? If so, can you provide the terminal output when you run the command or paste the full log into gist.

**Comment by privatezero** [comment]
Yes - test001.dv exists and test001.dv.dvrescue.xml is generated correctly (so also exists).

See [here](https://gist.github.com/privatezero/d84f132defd2671e2514ed7188bc4b9f) for gist of log.

Terminal (cmd) output of running that command (with quoting paths) is:

>"C:/Program Files/dvrescue/cygwin/bin/bash.exe" "C:/Program Files/dvrescue/tools/dvpackager" -v -X -a n -T /cygdrive/D/test001.dv.dvrescue.xml /cygdrive/D/test001.dv
> C:/Program Files/dvrescue/tools/dvpackager: line 692: basename: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 699: dirname: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 591: tput: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 592: tput: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 593: tput: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 594: tput: command not found
> C:/Program Files/dvrescue/tools/dvpackager: line 595: tput: command not found
> Error: there are additional unused arguments (-T /cygdrive/D/test001.dv.dvrescue.xml /cygdrive/D/test001.dv). Please reference the DV file last.
> C:/Program Files/dvrescue/tools/dvpackager: line 6: cat: command not found

**Comment by g-maxime** [comment]
Same on macOS with spaces in install path...

Script paths passed as bash arguments seems no quoted.
(Same for paths passed as arguments for scripts)

**Comment by g-maxime** [comment]
Fixed for macOS with [this snapshot](https://mediaarea.net/download/snapshots/binary/dvrescue-gui/20221008-2), please try Windows version.

The added patch: https://github.com/g-maxime/dvrescue/commit/c87b43709fdfa3f2375db5b708d58c6e10d80687

**Comment by privatezero** [comment]
I've just tested version 20221008-2  on Windows 10 and it looks like there is still an issue with spaces in the path. When I install dvrescue-gui via the installer, which places it into `Program FIles` segmentation still is broken. The log just displays the command with no exit status or obvious error.

>  C:/Program Files/dvrescue/cygwin/bin/bash.exe C:/Program Files/dvrescue/tools/dvpackager -v -X  -s -d -t -a n -T /cygdrive/D/test001.dv.dvrescue.xml /cygdrive/D/test001.dv

If I download the GUI ZIP archive and run it in a directory with no spaces in the path segmentation seems to function as expected (although I run into permissions errors when trying to package, but I assume that is expected from bypassing the installer).

**Comment by JeromeMartinez** [comment]
I installed in a directory without spaces and packaging works for "part1" then fails.

~~~
[...]

#Prepping a mapping for 2 channel input ().

#Writing a chapter track at /tmp/dvpackager.r2DhQ6.ffmetadata.

#Found 3 point(s) for chapter marks.

#Chapter: 00:00:00.000000-00:00:03.103100 (0-310310): 00:00:00;00

#Chapter: 00:00:03.103100-00:00:03.403400 (310310-340340): 00:00:03;03

#Chapter: 00:00:03.403400-00:00:15.015000 (340340-1501500): 00:00:00:09

#Trying to run: /cygdrive/c/temp/dvrescue/scripts/ffmpeg.sh  -y

[dv @ 000002E55A20B0C0] Detected timecode is invalid

[dvvideo @ 000002E55A2B5A00] Concealing bitstream errors

    Last message repeated 46 times
[dv @ 000002E55A20B0C0] Estimating duration from bitrate, this may be inaccurate
Input #0, dv, from 'subfile,,start,0,end,54000000,,:Z:\DVRescue_Test\DVRescue_Results\Example.dv':
  Duration: 00:00:15.02, start: 0.000000, bitrate: 28771 kb/s
  Stream #0:0: Video: dvvideo, yuv411p, 720x480 [SAR 8:9 DAR 4:3], 25000 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn
  Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
Input #1, ffmetadata, from 'C:\temp\dvrescue\cygwin\tmp\dvpackager.r2DhQ6.ffmetadata':
  Duration: 00:00:15.02, start: 0.000000, bitrate: 0 kb/s
  Chapters:
    Chapter #1:0: start 0.000000, end 3.103100
      Metadata:
        title           : 00:00:00;00
    Chapter #1:1: start 3.103100, end 3.403400
      Metadata:
        title           : 00:00:03;03
    Chapter #1:2: start 3.403400, end 15.015000
      Metadata:
        title           : 00:00:00:09
Overriding aspect ratio with stream copy may produce invalid files
Stream mapping:
  Stream #0:1 (pcm_s16le) -> aresample:default
  Stream #0:0 -> #0:0 (copy)
  aresample:default -> Stream #0:1 (pcm_s16le)

Output #0, mov, to 'Z:\DVRescue_Test\DVRescue_Results\Example_part1.mov':
  Metadata:
    timecode        : 00:00:00;00
    encoder         : Lavf59.34.100
  Chapters:
    Chapter #0:0: start 0.000000, end 3.103100
      Metadata:
        title           : 00:00:00;00
    Chapter #0:1: start 3.103100, end 3.403400
      Metadata:
        title           : 00:00:03;03
    Chapter #0:2: start 3.403400, end 15.015000
      Metadata:
        title           : 00:00:00:09
  Stream #0:0: Video: dvvideo (dvcp / 0x70637664), yuv411p, 720x480 [SAR 8:9 DAR 4:3], q=2-31, 25000 kb/s, 29.97 fps, 29.97 tbr, 30k tbn
  Stream #0:1: Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s
    Metadata:
      encoder         : Lavc59.50.100 pcm_s16le
frame=    0 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    

frame=  450 fps=0.0 q=-1.0 Lsize=   55558kB time=00:00:14.98 bitrate=30379.1kbits/s speed= 358x    
video:52734kB audio:2815kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.014743%

#AUD_STREAM_COUNT=(2
)

(standard_in) 1: illegal character: ^M
(standard_in) 1: illegal character: ^M

#VID_DUR=(15015
), AUD_DIR=(15015
), DUR_DIFF=()

(standard_in) 1: syntax error

ERROR: In Example_part1.mov the video track is 15015
 milliseconds and the audio track is 15015
. These tracks may lose sync.

### Done:seg_input=1|seg_output=1|output_frames=450|input_frames=450|audio_fill=0|output_file=/cygdrive/Z/DVRescue_Test/DVRescue_Results/Example_part1.mov

### Packaging error: audio-video-duration-mismatch

### Packaging finished: /cygdrive/Z/DVRescue_Test/DVRescue_Results/Example_part1.mov

Packaging Example.dv
# Segmentation options. Split on: Recording_Start_Marker = 0, Recording_Timestamp_Jump = 0, Timecode_Jump = 0, Audio_characteristics_change = 0, Aspect_Ratio_change = 1
#         St='Flagged Start of a recording', ncTC='non-continuous timecode value', ncR='non-continuous recording timestamp value'
  # | PTS Range                         | Duration | Frame Range         | Byte Range                | Timecode    | Recording Timestamp    | Size      | Frame Rate | DAR   | ChSub | Audio     | St | ncTC | ncR |
  1 | 00:00:00.000000 - 00:00:15.015000 |   15.015 |        0 -      449 |           0 -    54000000 | 00:00:00;00 |                        |   720x480 | 30000/1001 |   4/3 | 4:1:1 | 2ch 48000 |  1 |      |     |
~~~

**Comment by JeromeMartinez** [comment]
[The fail with install dir without space is fixed](https://github.com/mipops/dvrescue/pull/598), so issue is "only" with install dir with space.

**Comment by dericed** [comment]
Not sure where to look next. I think I'd need a new log from windows after https://github.com/mipops/dvrescue/pull/598 was applied.

**Comment by JeromeMartinez** [comment]
Setup: installed in `C:\Program files\dvrescue` then `C:\Program files\dvrescue` copied to `C:\Temp\dvrescue`

If:
- Launched from `C:\Program files\dvrescue` and configured with `C:\Program files\dvrescue`
- Launched from `C:\Program files\dvrescue` and configured with `C:\Temp\dvrescue`

```
[...]
C:/Program Files/dvrescue/cygwin/bin/bash.exe C:/Program Files/dvrescue/tools/dvpackager -v -X  -F  -D  -M  -z -a n -o /cygdrive/Z/DVRescue_Test/DVRescue_Results -x /cygdrive/Z/DVRescue_Test/DVRescue_Results/Example.dv.dvrescue.xml /cygdrive/Z/DVRescue_Test/DVRescue_Results/Example.dv


#CONDENSE_OPTS is set to -s

which: no xmlstarlet in (/cygdrive/c/program files/dvrescue:/cygdrive/c/program files/dvrescue:/cygdrive/c/program files/dvrescue:/cygdrive/c/program files/dvrescue:/usr/bin:/cygdrive/c/Program Files/dvrescue/scripts:/cygdrive/c/Program Files/dvrescue/tools:/cygdrive/c/Program Files/dvrescue:/cygdrive/c/Program Files (x86)/Embarcadero/Studio/20.0/bin:/cygdrive/c/Users/Public/Documents/Embarcadero/Studio/20.0/Bpl:/cygdrive/c/Program Files (x86)/Embarcadero/Studio/20.0/bin64:/cygdrive/c/Users/Public/Documents/Embarcadero/Studio/20.0/Bpl/Win64:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/libnvvp:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v6.5/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v6.5/libnvvp:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/xampp/php:/cygdrive/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Embarcadero/RAD Studio/7.0/bin:/cygdrive/c/Users/Public/Documents/RAD Studio/7.0/Bpl:/cygdrive/c/Program Files (x86)/Embarcadero/Studio/19.0/bin:/cygdrive/c/Users/Public/Documents/Embarcadero/Studio/19.0/Bpl:/cygdrive/c/Program Files (x86)/Embarcadero/Studio/19.0/bin64:/cygdrive/c/Users/Public/Documents/Embarcadero/Studio/19.0/Bpl/Win64:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program Files/FileBot:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program Files/dotnet:/cygdrive/c/Go/bin:/cygdrive/c/ProgramData/ComposerSetup/bin:/cygdrive/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Program Files/TortoiseGit/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program Files/OpenVPN/bin:/cygdrive/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/dotnet:/cygdrive/c/Users/jerom/.cargo/bin:/cygdrive/c/Users/jerom/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Users/jerom/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin:/cygdrive/c/Users/jerom/AppData/Roaming/npm:/cygdrive/c/Users/jerom/go/bin:/cygdrive/c/Users/jerom/AppData/Roaming/Composer/vendor/bin:/cygdrive/c/Users/jerom/AppData/Local/Programs/Microsoft VS Code/bin:/cygdrive/c/Users/jerom/.dotnet/tools)

The xmlstarlet command-line tool is not found.
```
(first command on a single line normal?)

If:
- Launched from `C:\Temp\dvrescue` and configured with `C:\Program files\dvrescue`
- Launched from `C:\Temp\dvrescue` and configured with `C:\Temp\dvrescue`

```
[...]
C:/temp/dvrescue/cygwin/bin/bash.exe C:/temp/dvrescue/tools/dvpackager -v -X /cygdrive/c/temp/dvrescue/scripts/xml.sh
 -F /cygdrive/c/temp/dvrescue/scripts/ffmpeg.sh
 -D /cygdrive/c/temp/dvrescue/scripts/dvrescue.sh
 -M /cygdrive/c/temp/dvrescue/scripts/mediainfo.sh
 -z -a n -o /cygdrive/Z/DVRescue_Test/DVRescue_Results -x /cygdrive/Z/DVRescue_Test/DVRescue_Results/Example.dv.dvrescue.xml /cygdrive/Z/DVRescue_Test/DVRescue_Results/Example.dv

#CONDENSE_OPTS is set to -s

#Using /cygdrive/c/temp/dvrescue/scripts/ffmpeg.sh for ffmpeg operations.

#No xmlstarlet error
[...]
```
