### ISSUE TITLE
dvanalysis + dvpackager cannot load large files

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#618]
Files over 4GB seem to make the GUI crash when attempting to load into either dvpackager or dvanalysis. I've had to force quit for anything larger than 4GB when using version 20221012.

**Comment by privatezero** [comment]
fwiw I just tested on v. 20221017 on Ubuntu, and it did not crash with a 4.3 GB file, so possibly a mac only issue

**Comment by dericed** [comment]
I'm on an M1 Macbook Air with Big Sur and the 1017 build processed an 11GB file of my really fast. I just ran it through packaging and all good there too. @libbyhopfauf, when the gui crashed, did you still get an xml output? If you run `dvrescue bigfile.dv > hey.xml` does it crash? @JeromeMartinez any ideas?

**Comment by libbyhopfauf** [comment]
@dericed nope, no XML output when it crashes or I have to force quit. I can test that command when I have access to decks later today. I was using a 2012 Mac Mini which is running Catalina 10.15.7. I'll test on a new computer and see if it's a Mac issue in general or maybe just old computer one.

**Comment by dericed** [comment]
Oh I think I found this crash too and it was related to what was fixed in https://github.com/mipops/dvrescue/pull/621/commits/927223e3fcc3c62993c45035a7fb8a6ae3791f63. Can you retest with the 2022-10-20 option for the crash scenario?

**Comment by libbyhopfauf** [comment]
Yep, will do once I have access to decks.

**Comment by libbyhopfauf** [comment]
Tested this on a 2014 Mac Mini also running Catalina 10.15.7, as well as a 2019 MacBook Pro running Big Sur 11.6.7 and am still getting the same result as with the older computer. Both analysis and package cannot handle the larger files created at MIPoPS that we need to package according to the audio rate changes. We're just getting endless spinning pink wheel.

**Comment by dericed** [comment]
yikes, what if you dig the command to generate the xml from the debug window and just run that in terminal directly?

**Comment by libbyhopfauf** [comment]
There's no problem using the XML and the CLI to package. I just can't analysis or package in the GUI with larger files. It also seems like sometimes it will segment and sometimes it won't. CLIs consistently accurately package according to the segmenting rules specified in the command.

**Comment by dericed** [comment]
hmmm, by `will segment` do you mean outputting segmenting movs or just displaying the table of what the outputs would be? in either case, could you share the xml and some steps and I can try to recreate.

**Comment by libbyhopfauf** [comment]
I think the main part of this issues was resolved with limiting non-consecutive timecode markers to 100.

<img width="1792" alt="Screenshot 2023-01-25 at 11 56 05 AM" src="https://user-images.githubusercontent.com/13877631/214675717-b12c240a-6512-4943-8dcb-2b4f466d591f.png">
