### ISSUE TITLE
newb- audio artifacts on playback, not in camera 

### ISSUE THREAD

**Issue by eastnarcissus** [mipops/dvrescue#719]
so far dv rescue has been the only solution to transferring mini dv that has worked seamlessly for me, the other program which was somewhat effective was lifelix but it would constantly stop my tapes and require me to restart.

dv rescue worked flawlessly for the first several tapes but the files started producing audio artifacts after awhile. this is not a problem with the tapes or the camera, as when i listen through the in-camera audio during playback there are no artifacts. i also don't believe it's a problem with the firewire connection as transferring the tapes in other programs doesn't produce the artifacts. i've transferred the same tape twice and the artifacts appear in different places on the file, but are still there. i was so happy that dv rescue actually worked, and this was my first time operating in any capacity with homebrew or really terminal for that matter, so this problem is a huge headache after working for weeks to develop the hundreds of hours of tapes that i have.

if anyone has experience with this problem or any ideas i would really appreciate it, thank you! i can attach an example of the issue audio as well if that would help. it sounds like a distorted spike in audio.

**Comment by dericed** [comment]
Hi. Thanks for all the kind words. Are you listening to the audio of the captured dv file? If so, could you run the file through dvpackager, that should resolve the audio playback issue. I suspect your file mixes sampling rates.

**Comment by eastnarcissus** [comment]
will try running the file through dvpackager now and return results, and
yes i am listening to the captured dv. thanks very much! will report back.

**Comment by eastnarcissus** [comment]
So interesting results- once packaged the audio artifacts are still present
but they are a lot quieter, yet when listening to the playback on the
camera they aren't present at all. any idea why that might be and how to
mitigate this?

**Comment by libbyhopfauf** [comment]
@eastnarcissus what audio channels is your deck set to playback? Also what segmenting rules did you use for packaging the captured dv file?
